name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Verify Node.js version
      run: node -v

    - name: Verify npm version
      run: npm -v

    - name: Install dependencies
      run: |
        npm install
        echo "Dependencies installed successfully."

    - name: Run tests
      run: |
        echo "Starting tests..."
        npm test
